language: node_js
sudo: required
services:
  - docker
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "7"
  - "8"
before_install:
  - docker run --name ravel-postgres-test -d -e POSTGRES_USER=ravel -e POSTGRES_PASSWORD=password -p 15432:5432 postgres:10.0-alpine
  - docker ps -a
  - $CXX --version
  - npm install
after_script:
  - codeclimate-test-reporter < reports/lcov.info
  - docker rm -fv ravel-postgres-test
