language: node_js
sudo: required
dist: focal
services:
  - docker
node_js:
  - "10"
  - "12"
before_install:
  - docker run --name ravel-postgres-test -d -e POSTGRES_USER=ravel -e POSTGRES_PASSWORD=password -p 15432:5432 postgres:12.4-alpine
  - docker ps -a
  - $CXX --version
  - npm install
after_script:
  - codeclimate-test-reporter < reports/lcov.info
  - docker rm -fv ravel-postgres-test
