language: node_js
sudo: required
dist: focal
services:
  - docker
node_js:
  - "10"
  - "12"
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - docker run --name ravel-postgres-test -d -e POSTGRES_USER=ravel -e POSTGRES_PASSWORD=password -p 15432:5432 postgres:12.4-alpine
  - docker ps -a
  - npm install
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - docker rm -fv ravel-postgres-test
